appointments/urls.py
from django.urls import path
from .views import *

app_name = 'appointments'

urlpatterns = [

    path('queue', d_queue,  name='d_queue'),
    path('queue/<str:selected_date>/', d_queue, name='d_queue'),

    path('', p_appointments_list,  name='p_appointments'),
    path('referrals', p_referrals_list,  name='p_referrals'),

    path('specialities', p_specialities_list,  name='p_specialities'),
    path('speciality/', p_speciality, name='p_speciality'),
    path('speciality/<int:speciality_id>/', p_speciality, name='p_speciality'),

    path('create_appointment/<int:doctor_id>/',
         p_create_appointment, name='p_create_appointment'),
    path('save_appointment/', p_save_appointment, name='p_save_appointment'),

    path('doctor_available_slots/', doctor_available_slots,
         name='doctor_available_slots'),

    path('confirm_appointment/', d_confirm_appointment,
         name='d_confirm_appointment'),
    path('cancel_appointment/', p_cancel_appointment,
         name='p_cancel_appointment'),

    path('create_referral/', d_create_referral, name='d_create_referral'),







]

ereg/urls.py
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('schedule/', include('schedule.urls')),
    path('appointments/', include('appointments.urls')),
    path('payments/', include('payments.urls')),

    path('select2/', include('django_select2.urls')),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path
from .views import *

app_name = 'payments'

urlpatterns = [

    path('', p_payments_list, name='p_payments'),
    path('<int:invoice_id>/', payment_detail, name='payment_detail'),
    path('create_invoice/', d_create_invoice, name='d_create_invoice'),


]

schedule/urls.py
from django.urls import path
from .views import *

app_name = 'schedule'

urlpatterns = [
    path('', get_schedule, name='schedule'),
    path('<str:date_str>/', get_schedule, name='schedule'),

]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('ereg/', e_reg,  name='e_reg'),
    path('patients/', d_patients_list,  name='d_patients_list'),

]

payments/models.py
from django.db import models
from users.models import Doctor, Patient
from django.utils import timezone
# Create your models here.


class Invoice(models.Model):
    class Meta:
        verbose_name = 'Счет'
        verbose_name_plural = 'Счета'

    class Status(models.TextChoices):
        CONFIRMED = 'CONFIRMED', 'Оплачено'
        WAITING = 'WAITING', 'Не оплачено!'

    SEX_CHOICES = [
        (1, 'Мужчина'),
        (0, 'Женщина')
    ]

    creation_date = models.DateTimeField('Дата создания', auto_now_add=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE,
                                related_name='patient_invoices', verbose_name='Пациент')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE,
                               related_name='doctor_invoices', verbose_name='Врач-исполнитель')
    services = models.ManyToManyField(
        'Service', through='InvoiceService', verbose_name='Услуги')
    payment_date = models.DateTimeField('Дата оплаты', null=True, blank=True)
    total_amount = models.DecimalField(
        'Сумма', max_digits=8, decimal_places=2, default=0)
    status = models.CharField('Статус', max_length=100,
                              choices=Status.choices, default=Status.WAITING)

    @property
    def get_status(self):
        return self.get_status_display()

    def __str__(self) -> str:
        formatted_date = self.creation_date.strftime('%d.%m.%Y')
        return f'Счет пациента id{self.patient.id} от {formatted_date}'

    def save(self, *args, **kwargs):
        if self.status == 'CONFIRMED' and not self.payment_date:
            self.payment_date = timezone.now()
        elif self.status != 'CONFIRMED':
            self.payment_date = None
        super().save(*args, **kwargs)


class Service(models.Model):
    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Оказываемые услуги'

    name = models.CharField('Наименование', max_length=100)
    price = models.DecimalField('Цена (р.)', max_digits=8, decimal_places=2)

    def __str__(self):
        return f"{self.name} - {self.price}"


class InvoiceService(models.Model):
    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Оказанные услуги'
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, verbose_name='Услуга')
    quantity = models.PositiveIntegerField('Количество', default=1)
    total_price = models.DecimalField(
        'Цена (р.)', max_digits=8, decimal_places=2, default=0)

    def __str__(self):
        return self.service.name

schedule/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from users.models import *
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class Schedule(models.Model):
    name = models.CharField('Наименование', max_length=150,
                            help_text='Напр. август, 1-я смена', default='Расписание')
    doctors = models.ManyToManyField(
        Doctor, verbose_name='Медработники', related_name='schedules')
    start_date = models.DateField('Период с')
    end_date = models.DateField('Период до')
    monday_start = models.TimeField('Начало', null=True, blank=True)
    monday_end = models.TimeField('Конец', null=True, blank=True)
    tuesday_start = models.TimeField('Начало', null=True, blank=True)
    tuesday_end = models.TimeField('Конец', null=True, blank=True)
    wednesday_start = models.TimeField('Начало', null=True, blank=True)
    wednesday_end = models.TimeField('Конец', null=True, blank=True)
    thursday_start = models.TimeField('Начало', null=True, blank=True)
    thursday_end = models.TimeField('Конец', null=True, blank=True)
    friday_start = models.TimeField('Начало', null=True, blank=True)
    friday_end = models.TimeField('Конец', null=True, blank=True)
    saturday_start = models.TimeField('Начало', null=True, blank=True)
    saturday_end = models.TimeField('Конец', null=True, blank=True)
    sunday_start = models.TimeField('Начало', null=True, blank=True)
    sunday_end = models.TimeField('Конец', null=True, blank=True)

    class Meta:
        verbose_name = 'Расписание'
        verbose_name_plural = 'Расписания'

    def __str__(self):
        return self.name


class ScheduleException(models.Model):
    doctor = models.ForeignKey(
        Doctor, verbose_name='Врач', on_delete=models.CASCADE)
    start_date = models.DateField('Период с')
    end_date = models.DateField('Период до')
    start_time = models.TimeField(
        'Начало', null=True, blank=True, help_text='Оставьте пустым для пропуска')
    end_time = models.TimeField('Конец', null=True, blank=True)

    class Meta:
        verbose_name = 'Изменение в расписании '
        verbose_name_plural = 'Изменения в расписании (исключения)'

    def __str__(self):
        start_date_str = self.start_date.strftime('%d.%m.%Y')
        end_date_str = self.end_date.strftime('%d.%m.%Y')
        return f'{start_date_str}-{end_date_str}, {self.doctor}'

    def clean(self):
        if self.start_date and self.end_date:
            if self.start_date > self.end_date:
                raise ValidationError(
                    _('Start date cannot be later than end date.'))
            if self.start_date == self.end_date and self.start_time >= self.end_time:
                raise ValidationError(
                    _('Start time cannot be later than or equal to end time for the same day.'))

        if self.start_date == datetime.today().date() and self.start_time <= datetime.now().time():
            raise ValidationError(
                _('Start time cannot be earlier than current time.'))

    def save(self, *args, **kwargs):
        if self.start_time and self.end_time and self.start_time >= self.end_time:
            raise ValueError(
                "Время начала не может быть больше времени окончания")

        if self.pk is None:  # объект еще не сохранен, создаем новую запись
            # Удаляем все записи с таким же диапазоном дат
            ScheduleException.objects.filter(
                doctor=self.doctor,
                start_date=self.start_date,
                end_date=self.end_date
            ).delete()

        super().save(*args, **kwargs)

schedule/forms.py
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth import get_user_model
from .models import Schedule
from users.models import *
from django.core.exceptions import ValidationError

from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    doctors = forms.ModelMultipleChoiceField(
        queryset=Doctor.objects.order_by(
            'doctorproperties__speciality', 'last_name', 'first_name'),
        widget=FilteredSelectMultiple('специалисты', False),
        label='Медработники'
    )
    monday_start = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Начало', required=False, help_text='оставьте пустым для пропуска рабочего дня')
    monday_end = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Конец', required=False)
    tuesday_start = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Начало', required=False,  help_text='оставьте пустым для пропуска рабочего дня')
    tuesday_end = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Конец', required=False)
    wednesday_start = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Начало', required=False,  help_text='оставьте пустым для пропуска рабочего дня')
    wednesday_end = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Конец', required=False)
    thursday_start = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Начало', required=False,  help_text='оставьте пустым для пропуска рабочего дня')
    thursday_end = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Конец', required=False)
    friday_start = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Начало', required=False,  help_text='оставьте пустым для пропуска рабочего дня')
    friday_end = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Конец', required=False)
    saturday_start = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Начало', required=False,  help_text='оставьте пустым для пропуска рабочего дня')
    saturday_end = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Конец', required=False)
    sunday_start = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Начало', required=False, help_text='оставьте пустым для пропуска рабочего дня')
    sunday_end = forms.TimeField(widget=forms.TimeInput(
        attrs={'type': 'time'}), label='Конец', required=False)

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        doctors = cleaned_data.get('doctors')
        if Schedule.objects.count() > 0:
            for doctor in doctors:
                schedules = Schedule.objects.filter(
                    doctors=doctor,
                    start_date__lte=end_date,
                    end_date__gte=start_date,
                ).exclude(pk=self.instance.pk if self.instance else None)

                if schedules.exists():
                    raise ValidationError(
                        f"Расписание для работника \"{doctor}\" пересекается с другим его расписанием!"
                    )
        return cleaned_data

    class Meta:
        model = Schedule
        fields = '__all__'

    def save(self, commit=True):
        schedule = super().save(commit=False)
        if commit:
            if not schedule.id:
                schedule.save()
            schedule.doctor.set(self.cleaned_data['doctors'])
            self.save_m2m()
            schedule.save()
        return schedule

schedule/views.py
from django.shortcuts import render, redirect
from datetime import datetime, timedelta
from django.http import JsonResponse
from datetime import timedelta
from users.models import *
from django.urls import reverse
from .models import ScheduleException
from .models import *


def get_schedule(request, date_str=None):
    if request.method == "POST":

        doctor_id = request.POST.get('doctor_id')
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        start_time = request.POST.get('start_time')
        end_time = request.POST.get('end_time')

        doctor = Doctor.objects.get(id=doctor_id)
        if len(start_time) > 0:
            exception = ScheduleException(
                doctor=doctor, start_date=start_date, end_date=end_date, start_time=start_time, end_time=end_time)
        else:
            exception = ScheduleException(
                doctor=doctor, start_date=start_date, end_date=end_date)

        exception.save()

        return JsonResponse({'status': 'ok'})

    # Вычисляем начальную дату
    if date_str:
        date = datetime.strptime(date_str, '%d-%m-%Y').date()
    else:
        date = datetime.today().date()
    # Начинаем с понедельника текущей недели
    date = date - timedelta(days=date.weekday())

    # Добавляем ссылки на даты через 7 дней и 7 дней назад
    prev_week = (date - timedelta(days=7)).strftime('%d-%m-%Y')
    next_week = (date + timedelta(days=7)).strftime('%d-%m-%Y')
    context = {
        'prev_week_url': reverse('schedule:schedule', args=[prev_week]),
        'next_week_url': reverse('schedule:schedule', args=[next_week]),
    }
    current_week = (date - timedelta(days=date.weekday())) == (
        datetime.today().date() - timedelta(days=datetime.today().date().weekday()))
    if current_week:
        context['prev_week_url'] = None

    # Берем всех врачей, если пользователь является админом, иначе только видимых врачей
    if request.user.is_staff:
        doctors = Doctor.objects.all()
    else:
        doctors = Doctor.objects.filter(doctorproperties__visible=True)

    date_list = [date + timedelta(days=i) for i in range(7)]

    # Получаем расписание каждого врача и сохраняем в контекст
    s = {}
    for doctor in doctors:
        schedules = []
        for d in date_list:
            schedule = doctor.get_schedule_for_date_str(d)
            schedules.append(schedule)
        s[doctor.id] = schedules

    context['schedules'] = s
    context['date_list'] = date_list
    context['doctors'] = doctors
    context['range'] = range(7)

    if request.user.is_staff:
        context['template'] = 'admin/base.html'
    elif request.user.role == 'PATIENT':
        context['template'] = 'patient_base.html'
    elif request.user.role == 'DOCTOR':
        context['template'] = 'doctor_base.html'
    else:
        return redirect('login')

    return render(request, 'schedule.html', context)

templates/p_appointments_list.html
{% extends 'patient_base.html' %}

{% block title %}Мои записи на прием{% endblock %}



{% block content %}
    <h3>Мои записи на прием</h3>
    <div class="row">
        <div class="col-lg-12">
            <div class="d-flex justify-content-end mb-3">
                <a href="{% url 'appointments:p_specialities' %}" class="btn btn-success">Записаться на прием</a>
            </div>
        </div>
        <div class="col-lg-12">
            <h1>{{ title }}</h1>
            {% if not appointments_list %}
                <h5 class="text-center">У вас еще нет записей</h5>
            {% else %}
                <table class="table table-hover">
                    <thead>
                        <tr>
                            
                            <th>Специальность</th>
                            <th>ФИО Врача</th>
                            <th>Каб.</th>
                            <th>Дата и время</th>
                            <th>Статус приема</th>
                            
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for appointment in appointments_list %}
                            <tr>
                                
                                <td>{{ appointment.doctor.doctorproperties.speciality.name }}</td>
                                <td>{{ appointment.doctor.get_full_name }}</td>
                                <td>{{ appointment.doctor.doctorproperties.cabinet }}</td>
                                
                                <td>{{ appointment.date }} {{appointment.time}}</td>
                                <td class="align-middle ">
                                    
                                    <span class=" justify-content-center badge w-100 {% if appointment.status == 'WAITING' %}bg-warning {% elif appointment.status == 'COMPLETED' %}bg-success {% elif appointment.status == 'MISSED' or  appointment.status == 'CANCELLED' or  appointment.status == 'PATIENT_CANCELLED' %}bg-danger{% endif %}">
                                      {{ appointment.get_status }}
                                    </span>
                                </td>
                                <td class="align-middle">
                                {%if appointment.status == 'WAITING'%}<div class="d-flex justify-content-center ">
                                    <a href="#" data-appointment-id="{{appointment.id}}" class="btn btn-sm btn-outline-danger cancel-appointment-btn ">Отменить</a>
                                </div>{%endif%}
                            </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>




    <div class="modal fade" id="cancelModal" tabindex="-1" aria-labelledby="cancelModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="cancelModalLabel">Отменить запись?</h5>
            </div>
            <div class="modal-body">
              <p><b>Врач: </b><span id="nametext"></span></p>
              <p><b>Время записи:</b> <span id="timetext"></span> </p>
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
              <a id="cancelBtn" href="#" class="btn btn-danger">Оменить запись</a>
            </div>
          </div>
        </div>
      </div>
      
    
      <script>

        $(document).ready(function() {
            

            $(document).on('click', '.cancel-appointment-btn', function() {
                var row = $(this).data('row');
                var appointmentId = $(this).data('appointment-id');
        
                // Отобразить модальное окно с подтверждением
                $('#cancelModal').modal('show');
               
                var rowIndex = $(this).closest('tr').index();
                
                // Получение текста из первого столбца таблицы для выбранной строки
                 
                $('#nametext').text($('table tr').eq(rowIndex+1).find('td:eq(1)').text()+' ('+$('table tr').eq(rowIndex+1).find('td:eq(0)').text()+')');
                $('#timetext').text($('table tr').eq(rowIndex+1).find('td:eq(2)').text());
                
                
                // Обработчик события нажатия кнопки подтверждения в модальном окне
                $('#cancelModal').on('click', '#cancelBtn', function() {
                    var selectedDate = $('#selected_date').val();
                  // Отправить запрос на сервер
                  $.ajax({
                    url: "{%url 'appointments:p_cancel_appointment'%}",
                    method: 'POST',
                    data: {
                      appointment_id: appointmentId,
                      
                      csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function(response) {
                       // Обработка успешного ответа от сервера
                      console.log(response);
                      window.location.href = "{% url 'appointments:p_appointments' %}";
                      // Дополнительный код, если необходимо
                    },
                    error: function(xhr, errmsg, err) {
                      // Обработка ошибки
                      
                      console.log(xhr.status + ': ' + xhr.responseText);
                      // Дополнительный код, если необходимо
                    }
                  });
              
                  // Закрыть модальное окно
                  $('#cancelModal').modal('hide');
                });
              });
              $(document).on('click', '.btn-secondary', function() {
                // Закрыть модальное окно
                $(this).closest('.modal').modal('hide');
              });
        });
        
              
      </script>


{% endblock %}

templates/p_create_appointment.html
{% extends 'patient_base.html' %}

{% load static %}

{% block title %}Записаться на прием{% endblock %}

{% block nav %}
    <li class="breadcrumb-item"><a href="{%url 'appointments:p_appointments'%}">Мои записи на прием</a></li> 
    <li class="breadcrumb-item"><a href="{%url 'appointments:p_specialities'%}">Записаться</a></li> 
    <li class="breadcrumb-item"><a href="{%url 'appointments:p_speciality' doctor.doctorproperties.speciality.id %}">{{ doctor.doctorproperties.speciality }}</a></li> 
    <li class="breadcrumb-item active">{{ doctor.get_full_name }}</li> 
{% endblock %}


{% block content %}


<div class="card m-2" style="max-width: 600px;">
    <div class="row no-gutters align-items-center">
      <div class="col-md-3 m-md-3 m-sm-0 my-1">
        {% if doctor.doctorproperties.image %}
          <div class="circle-avatar d-flex justify-content-center">
            <img style="max-width:250px; border-radius: 50%;" class="w-100" src="{{ doctor.doctorproperties.image.url }}" class="rounded-circle">
          </div>
        {% else %}
          <div class="circle-avatar d-flex justify-content-center">
            <img style="max-width:250px" class="w-100" src="{% static 'images/person-circle.svg' %}" class="rounded-circle">
          </div>
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{ doctor }}</h5>
          <p class="text-muted">{{ doctor.speciality }}</p>
          <div class="card-text"><b>Пол: </b>{% if doctor.sex %}мужчина{% else %}женщина{% endif %}</div>
          <div class="card-text"><b>Возраст: </b>{{ doctor.age }}</div>
          <br>
          <div class="card-text">{{ doctor.phone_number }}</div>
          <div class="card-text">{{ doctor.username }}</div>
        </div>
      </div>
    </div>
  </div>
  
  <h5 class="mx-2 mt-5" >Записаться на прием</h5>
  <form method="GET" class="form-inline m-2">
    <div class="form-group mr-2">
      <label for="selected_date">Выберите дату:</label>
      <input type="date" name="selected_date" id="selected_date" class="form-control mr-2 w-50">
      <input type="hidden" name="referral_id" value="{{ referral_id }}">
    </div>
    <button type="submit" class="btn btn-primary my-2">Поиск</button>
  </form>

  {% if selected_date %}
    <h4>Свободные места на {{ selected_date }}</h4>
    {% if available_slots %}
      <div style="max-width:700px" class="">
        {% for slot in available_slots %}
          <a style="min-width:100px;" class="btn btn-success min-w-100 m-1 slot">{{ slot }}</a>
        {% endfor %}
      </div>
    {% else %}
      <p>Нет доступных мест на выбранную дату.</p>
    {% endif %}
  {% endif %}
  <div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="confirmModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="confirmModalLabel">Подтверждение записи</h5>
        </div>
        <div class="modal-body">
          <p>{{ doctor }}?</p>
          <p>Дата и время приема: <span id="datetimetext">{{ selected_date }} </span> </p>
          <p>Записаться на прием?</p>
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
          <a id="confirmBtn" href="#" class="btn btn-primary">Записаться</a>
        </div>
      </div>
    </div>
  </div>
  <div id="error-container"></div>
  <script>
    $(document).ready(function() {
        // Получение значения параметра selected_date из URL-адреса
        var urlParams = new URLSearchParams(window.location.search);
        var selectedDate = urlParams.get('selected_date');
      
        // Установка значения параметра selected_date в поле ввода даты
        $('#selected_date').val(selectedDate);
      });
      
        $(document).on('click', '.slot', function() {

            var slot = $(this).text();
            var selectedDate = '{{ selected_date }}'; // Здесь нужно передать значение выбранной даты из вашего контекста
            
            
            // Отобразить модальное окно с подтверждением
            $('#confirmModal').modal('show');
            $('#datetimetext').text("{{selected_date}} "+slot)
          
            // Обработчик события нажатия кнопки подтверждения в модальном окне
            $('#confirmModal').on('click', '#confirmBtn', function() {
                var selectedDate = $('#selected_date').val();
              // Отправить запрос на сервер
              $.ajax({
                url: "{%url 'appointments:p_save_appointment'%}",
                method: 'POST',
                data: {
                  selected_date: selectedDate,
                  slot: slot,
                  doctor_id: {{doctor.id}},
                  {% if referral_id and referral_id != "None" %}
                      referral_id: {{ referral_id }},
                  {% endif %}
                  csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response) {
                  if (response.success) {
                    // Обработка успешного ответа от сервера
                    console.log(response.message);
                    window.location.href = "{% url 'appointments:p_appointments' %}";
                    // Дополнительный код, если необходимо
                  } else {
                    var errorAlert = $('<div class="alert alert-danger" role="alert">').text('Вы уже записаны на прием к этому врачу');
                      $('#error-container').empty().append(errorAlert);
                    // Вывод сообщения об ошибке
                    console.log(response.message);
                    // Дополнительный код, если необходимо
                  }
                },
                error: function(xhr, errmsg, err) {
                  // Обработка ошибки
                  
                  console.log(xhr.status + ': ' + xhr.responseText);
                  // Дополнительный код, если необходимо
                }
              });
          
              // Закрыть модальное окно
              $('#confirmModal').modal('hide');
            });
          });
          $(document).on('click', '.btn-secondary', function() {
            // Закрыть модальное окно
            $(this).closest('.modal').modal('hide');
          });
          
      
  </script>
{% endblock %}

templates/p_speciality.html
{% extends 'patient_base.html' %}
{%load static%}
{% block title %}Подобрать специалиста{% endblock %}

{% block nav %}
    <li class="breadcrumb-item"><a href="{%url 'appointments:p_appointments'%}">Мои записи на прием</a></li> 
    <li class="breadcrumb-item"><a href="{%url 'appointments:p_specialities'%}">Записаться</a></li> 
    <li class="breadcrumb-item active">{{ speciality.name }}</li> 
{% endblock %}


{% block content %}
<h3>Выберите врача: {{ speciality.name }}</h3>

<form method="GET" class="form-inline">
  <div class="form-group mb-2">
    <label for="selected_date" class="mr-2">Можете найти доступных врачей по дате:</label>
    <input type="date" name="selected_date" id="selected_date" class="form-control mr-2 w-50">
    <input type="hidden" name="referral_id" value="{{ referral_id }}">
  </div>
  <button type="submit" class="btn btn-primary mb-2">Поиск</button>
</form>


{% if doctors %}
    {%if selected_date%}
        <h5 class="text-center py-3">Врачи, доступные {{selected_date}}</h5>
    {%endif%}
  <table class="table">
    <thead>
      <tr>
        <th>Врач</th>
        {% if selected_date %}
          <th></th>
        {% endif %}
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for doctor in doctors %}
        <tr>
          <td>
            <div class="d-flex align-items-center">
              {% if doctor.doctorproperties.image %}
                <div class="circle-avatar">
                  <img width="55" src="{{ doctor.doctorproperties.image.url }}" alt="{{ doctor.get_full_name }}" class="rounded-circle me-3">
                </div>
              {% else %}

              <img width="55" src="{% static 'images/person-circle.svg' %}" alt="{{ doctor.get_full_name }}" class="rounded-circle me-3">
              {% endif %}
              <span class="ml-2">{{ doctor.get_full_name }}</span>
            </div>
          </td>
          <td class="col-md-4 col-sm-4 align-middle">
            <div class="d-flex justify-content-center">
            {%if selected_date%}
              <a href="{%url 'appointments:p_create_appointment' doctor.id%}?selected_date={{selected_date|date:'Y-m-d'}}&referral_id={{referral_id}}" class="btn btn-outline-success ">Записаться на прием</a>
            {%else%}
              <a href="{%url 'appointments:p_create_appointment' doctor.id%}?referral_id={{referral_id}}" class="btn btn-outline-success ">Записаться на прием</a>
            {%endif%}
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  {% if selected_date %}
    <h5 class="text-center py-3">Нет доступных врачей на выбранную дату</h5>
  {% else %}
    <p>Нет доступных врачей для выбранной специальности</p>
  {% endif %}
{% endif %}
<script>
    $(document).ready(function() {
        // Получение значения параметра selected_date из URL-адреса
        var urlParams = new URLSearchParams(window.location.search);
        var selectedDate = urlParams.get('selected_date');
      
        // Установка значения параметра selected_date в поле ввода даты
        $('#selected_date').val(selectedDate);
      });
</script>
{% endblock %}